-   id: textlint
    name: textlint
    entry: textlint
    language: node
    types: [text]
    additional_dependencies:
      - "textlint@12.1.1"
      - "textlint-filter-rule-allowlist@4.0.0"
      - "textlint-filter-rule-comments@1.2.2"
      - "textlint-rule-terminology@3.0.1"
      
